global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "springboot"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["logistics-tracking-app:8080"]

  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafka_exporter:9308"]
