server:
  port: 8080

spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 20000
      max-lifetime: 1740000
      connection-timeout: 30000
      leak-detection-threshold: 5000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
        max-wait: 2000ms

logging:
  level:
    root: INFO
    com.example.logisticstracking: DEBUG
  config: classpath:logback-spring.xml

splunk:
  url: http://localhost:8088
  token: 00000000-0000-0000-0000-000000000000
  index: main
  source: logistic-tracking
  sourcetype: _json

## ACTUATOR (Monitoramento)
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics,info
  metrics:
    enable:
      hikari: true
  info:
    env:
      enabled: true
    git:
      mode: full


## CLIENTS (APIs Externas)
dog-api-client:
  name: dogApiClient
  url: https://dogapi.dog
  path: /api/v1/facts

nager-date-client:
  name: nagerDateClient
  url: https://date.nager.at
  path: /api/v3/PublicHolidays/{year}/{countryCode}
