spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_db
    username: logistics_user
    password: logistics_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 10

  kafka:
    bootstrap-servers: localhost:9093
