server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS  # NEVER / DETECT / ALWAYS

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: logistics-tracking-group

logging:
  level:
    root: INFO
    # ou configure níveis específicos:
    # com.example.logisticstracking: DEBUG

