server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        max-wait: 2000ms

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: logistics-tracking-group

logging:
  level:
    root: INFO

#CLIENTS
dog-api-client:
  name: dogApiClient
  url: https://dogapi.dog
  path: /api/v1/facts

nager-date-client:
  name: nagerDateClient
  url: https://date.nager.at
  path: /api/v3/PublicHolidays/{year}/{countryCode}
